spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/atma_user_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange:
      name: user-exchange
      type: topic
    queue:
      name:
        user-info: user-queue
    routing-key:
      user-info: user.routing.key

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/